/* =====================================================================
   Omni — emoji.js
   The emoji picker's list. These are normal Unicode emoji (the same
   ones your keyboard has), so no images or libraries are needed.
   Each line is: "emoji  words to search for".
   ===================================================================== */
const EMOJI = (() => {
  const cats = {
    smileys: ['😀', 'Smileys', `
😀 grinning smile happy|😃 smiley happy|😄 smile laugh|😁 grin beaming|😆 laughing lol|😅 sweat smile phew|🤣 rofl rolling laughing|😂 joy tears laughing lol|🙂 slight smile|🙃 upside down silly|😉 wink|😊 blush happy|😇 angel innocent|🥰 love hearts|😍 heart eyes love|🤩 star struck wow|😘 kiss|😋 yum tasty|😛 tongue|😜 wink tongue crazy|🤪 zany crazy|😎 cool sunglasses|🤓 nerd glasses|🧐 monocle thinking|🤔 thinking hmm|🤨 raised eyebrow sus|😐 neutral meh|😑 expressionless|😶 no mouth quiet|🙄 eye roll|😏 smirk|😬 grimace awkward|😌 relieved calm|😔 pensive sad|😪 sleepy|😴 sleeping zzz|😷 mask sick|🤒 thermometer sick ill|🤢 nauseous sick|🤮 vomit sick|🥵 hot|🥶 cold freezing|🥳 party celebrate birthday|😵 dizzy|🤯 mind blown exploding|🤠 cowboy|😕 confused|😟 worried|🙁 frown sad|😮 open mouth wow surprised|😲 astonished shocked|😳 flushed embarrassed|🥺 pleading puppy eyes|😢 cry sad tear|😭 sob crying|😱 scream scared|😖 confounded|😣 persevere|😞 disappointed|😓 downcast sweat|😩 weary tired|😫 tired|🥱 yawn bored|😤 triumph huff|😡 angry mad rage|😠 angry|🤬 swearing cursing angry|😈 devil smiling|💀 skull dead lol|💩 poop|🤡 clown|👻 ghost boo|👽 alien|🤖 robot|😺 cat smile|😹 cat joy|😻 cat heart eyes`],
    people: ['👋', 'People', `
👋 wave hello hi bye|🤚 raised back hand|✋ raised hand high five stop|🖖 vulcan salute|👌 ok perfect|🤌 pinched fingers|✌️ peace victory|🤞 crossed fingers luck|🤟 love you|🤘 rock on horns|🤙 call me shaka|👈 point left|👉 point right|👆 point up|👇 point down|☝️ index up|👍 thumbs up like yes|👎 thumbs down no dislike|✊ fist raised|👊 fist bump punch|👏 clap applause|🙌 raising hands hooray|🫶 heart hands|👐 open hands|🤲 palms up|🤝 handshake deal|🙏 pray please thanks|✍️ writing|💪 muscle strong flex|🧠 brain smart|👀 eyes looking|👁️ eye|👄 mouth|👶 baby|🧒 child kid|👦 boy|👧 girl|🧑 person|👱 blond person|👨 man|👩 woman|🧓 older person|👴 grandpa old man|👵 grandma old woman|🙋 person raising hand|🙆 ok gesture|🙅 no gesture|🤷 shrug idk|🤦 facepalm|🧑‍🎓 student graduate|🧑‍🏫 teacher|🧑‍🔧 mechanic worker|🧑‍🏭 factory worker|👷 construction worker builder|🧑‍💻 coder technologist|🧑‍🍳 cook chef|🧑‍⚕️ doctor health|👮 police officer|🦸 superhero|🧙 wizard mage|🧛 vampire|🧟 zombie|🏃 running|💃 dancing|🕺 dance man|👪 family|🗣️ speaking`],
    animals: ['🐶', 'Animals & nature', `
🐶 dog puppy|🐱 cat kitten|🐭 mouse|🐹 hamster|🐰 rabbit bunny|🦊 fox|🐻 bear|🐼 panda|🐨 koala|🐯 tiger|🦁 lion|🐮 cow|🐷 pig|🐸 frog|🐵 monkey|🙈 see no evil monkey|🐔 chicken|🐧 penguin|🐦 bird|🐤 chick|🦆 duck|🦅 eagle|🦉 owl|🦇 bat|🐺 wolf|🐴 horse|🦄 unicorn|🐝 bee|🐛 bug caterpillar|🦋 butterfly|🐌 snail|🐞 ladybug|🐢 turtle|🐍 snake|🦎 lizard|🦖 t-rex dinosaur|🦕 dinosaur|🐙 octopus|🦑 squid|🦀 crab|🐠 fish tropical|🐬 dolphin|🐳 whale|🦈 shark|🐊 crocodile|🦓 zebra|🦒 giraffe|🐘 elephant|🦘 kangaroo|🐕 dog|🐈 cat|🐾 paw prints|🌵 cactus|🎄 christmas tree|🌲 evergreen tree|🌳 tree|🌴 palm tree|🌱 seedling plant|🍀 four leaf clover luck|🍁 maple leaf autumn|🌷 tulip flower|🌹 rose flower|🌻 sunflower|🌸 cherry blossom|🌞 sun face|🌝 moon face|⭐ star|🌟 glowing star|✨ sparkles|⚡ lightning zap|🔥 fire lit|🌈 rainbow|☀️ sun sunny|⛅ cloudy|🌧️ rain|❄️ snowflake snow cold|☃️ snowman|🌊 wave ocean water|🌍 earth world globe`],
    food: ['🍕', 'Food & drink', `
🍏 green apple|🍎 apple red|🍐 pear|🍊 orange|🍋 lemon|🍌 banana|🍉 watermelon|🍇 grapes|🍓 strawberry|🫐 blueberries|🍒 cherries|🍑 peach|🥭 mango|🍍 pineapple|🥥 coconut|🥝 kiwi|🍅 tomato|🥑 avocado|🥦 broccoli|🥕 carrot|🌽 corn|🥔 potato|🥐 croissant|🍞 bread|🧀 cheese|🥚 egg|🍳 cooking fried egg|🥞 pancakes|🧇 waffle|🥓 bacon|🍗 chicken leg|🍔 burger hamburger|🍟 fries chips|🍕 pizza|🌭 hot dog|🥪 sandwich|🌮 taco|🌯 burrito|🥗 salad|🍝 spaghetti pasta|🍜 noodles ramen|🍣 sushi|🍱 bento|🍛 curry rice|🍚 rice|🥟 dumpling|🍦 ice cream soft|🍨 ice cream|🍩 donut doughnut|🍪 cookie biscuit|🎂 birthday cake|🍰 cake slice|🧁 cupcake|🍫 chocolate|🍬 candy sweet|🍭 lollipop|🍿 popcorn movie|🥤 soda drink cup|🧃 juice box|🧋 bubble tea boba|☕ coffee tea hot|🍵 tea|🥛 milk|🍼 baby bottle|🧊 ice cube|🥄 spoon|🍴 fork knife|🍽️ plate dinner`],
    activities: ['⚽', 'Activities', `
⚽ soccer football|🏀 basketball|🏈 american football|⚾ baseball|🥎 softball|🎾 tennis|🏐 volleyball|🏉 rugby|🥏 frisbee|🎱 pool 8 ball|🏓 ping pong table tennis|🏸 badminton|🏒 hockey|🏏 cricket|⛳ golf|🏹 bow arrow archery|🎣 fishing|🥊 boxing glove|🥋 martial arts karate|⛸️ ice skate|🛹 skateboard|🛼 roller skate|🚴 cycling bike|🏊 swimming|🏆 trophy winner|🥇 gold medal first|🥈 silver medal second|🥉 bronze medal third|🏅 medal|🎖️ military medal|🎮 video game controller gaming|🕹️ joystick arcade|🎲 dice game|🧩 puzzle|♟️ chess|🎯 bullseye target|🎳 bowling|🎨 art palette paint|🎭 theatre drama|🎤 microphone sing karaoke|🎧 headphones music|🎼 music score|🎹 piano keyboard|🥁 drum|🎸 guitar|🎻 violin|🎺 trumpet|🎷 saxophone|🎬 clapper movie film|📸 camera photo|🎉 party popper celebrate tada|🎊 confetti|🎈 balloon|🎁 gift present|🎂 cake birthday|🎃 pumpkin halloween|🎄 christmas|🎆 fireworks|🎇 sparkler|🧨 firecracker|🎟️ ticket|🎪 circus tent|🏕️ camping|🏖️ beach|🚀 rocket launch|✈️ plane travel|🚗 car|🚌 bus|🚲 bicycle|⛵ sailboat`],
    objects: ['💡', 'Objects', `
⌚ watch|📱 phone mobile|💻 laptop computer|⌨️ keyboard|🖥️ desktop computer|🖨️ printer|🖱️ mouse computer|💾 floppy save|💿 disc cd|📷 camera|🎥 movie camera|📺 tv television|📻 radio|🔋 battery|🔌 plug|💡 light bulb idea|🔦 flashlight torch|🕯️ candle|📚 books study|📖 open book reading|📝 memo notes homework|✏️ pencil|🖊️ pen|🖍️ crayon|📏 ruler|📐 triangle ruler|📎 paperclip|📌 pushpin|📍 pin location|✂️ scissors|🗂️ dividers folders|📁 folder|📅 calendar date|📆 calendar|🗓️ planner schedule|📋 clipboard|📊 bar chart|📈 chart up growth|📉 chart down|🔒 lock locked|🔓 unlocked|🔑 key|🔨 hammer|🪓 axe|⛏️ pick|🔧 wrench spanner|🪛 screwdriver|🔩 nut bolt|⚙️ gear settings|🧱 brick|🪜 ladder|🧰 toolbox|🦺 safety vest hi vis|⛑️ helmet hard hat|🚧 construction barrier|🧲 magnet|🧪 test tube science|🔬 microscope|🔭 telescope|💊 pill medicine|🩹 bandage plaster|🧸 teddy bear|🎒 backpack school bag|👟 sneaker shoe|👕 t-shirt|🧢 cap|👓 glasses|💰 money bag|💵 dollar cash|💳 credit card|✉️ envelope mail|📦 package box|🏠 house home|🏫 school|🏢 office building|🏗️ construction crane building|⏰ alarm clock|⏳ hourglass time|🔔 bell notification|📣 megaphone announcement`],
    symbols: ['❤️', 'Symbols', `
❤️ red heart love|🧡 orange heart|💛 yellow heart|💚 green heart|💙 blue heart|💜 purple heart|🖤 black heart|🤍 white heart|🤎 brown heart|💔 broken heart|❣️ heart exclamation|💕 two hearts|💞 revolving hearts|💓 beating heart|💗 growing heart|💖 sparkling heart|💘 heart arrow|💝 heart gift|✅ check yes done|☑️ check box|✔️ check mark|❌ cross no wrong|❎ cross button|➕ plus|➖ minus|➗ divide|✖️ multiply|❓ question|❔ white question|❗ exclamation|‼️ double exclamation|⁉️ interrobang|💯 hundred perfect 100|🔴 red circle|🟠 orange circle|🟡 yellow circle|🟢 green circle|🔵 blue circle|🟣 purple circle|⚫ black circle|⚪ white circle|🟥 red square|🟩 green square|🟦 blue square|⬆️ up arrow|⬇️ down arrow|⬅️ left arrow|➡️ right arrow|🔄 repeat refresh|🔁 loop|▶️ play|⏸️ pause|⏹️ stop|⏭️ next|🔀 shuffle|🔇 mute|🔊 loud speaker|📢 loudspeaker|💬 speech bubble chat|💭 thought bubble|🗯️ anger bubble|♻️ recycle|⚠️ warning|🚫 prohibited no|⛔ no entry|🆗 ok button|🆕 new|🆒 cool button|🆓 free|🔝 top|🔜 soon|💤 zzz sleep|💢 anger|💥 boom collision|💫 dizzy star|🎵 music note|🎶 music notes|➰ curly loop|〰️ wavy dash|©️ copyright|®️ registered|™️ trademark|#️⃣ hash|🔢 numbers|🔤 abc letters|🏁 chequered flag finish|🚩 red flag|🏳️‍🌈 rainbow flag|🏴‍☠️ pirate flag`]
  };
  // Turn each big string into a list of { e: '😀', n: 'grinning smile happy' }
  const out = {};
  for (const [key, [icon, name, text]] of Object.entries(cats)) {
    out[key] = { icon, name, items: text.trim().split('|').map(s => { const i = s.indexOf(' '); return { e: s.slice(0, i), n: s.slice(i + 1) }; }) };
  }
  return out;
})();
